import { useState } from "react";
import { motion } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { FileText, Sparkles, Copy, Check } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface ProductSlot {
  id: string;
  title: string;
  features: string;
}

interface GeneratedDescription {
  title: string;
  content: string;
}

const emptySlots: ProductSlot[] = Array.from({ length: 5 }, (_, index) => ({
  id: String(index + 1),
  title: "",
  features: "",
}));

function toFeatureList(value: string) {
  return value
    .split(/[,\n]/)
    .map((item) => item.trim())
    .filter(Boolean)
    .slice(0, 5);
}


/**
 * PRODUCTION DESCRIPTION ENGINE v2.3 - SOFTWARE BRANDED
 * References the 'Phoenix Flow' engine but remains retail-neutral.
 */
function buildDescriptionContent(product: ProductSlot, _context: string) {
  const features = toFeatureList(product.features);
  const title = product.title.trim();

  // 1. Regulatory Safety (Remains generic for all customers)
  const isIngredientSensitive = [
    "protein", "shake", "supplement", "wellness", "coffee", 
    "ashwagandha", "berberine", "soap", "tea", "capsule", "fusion", "vitality"
  ].some(k => title.toLowerCase().includes(k));

  const bulletItems = features.length > 0
    ? features.map((feature) => `<li>${feature}</li>`).join("")
    : "<li>Professional grade materials</li><li>Built for durability</li><li>Optimized for daily use</li>";

  // 2. The FDA Safety Net (Value-add for paid users)
  const regulatoryNotice = isIngredientSensitive 
    ? `<div class="phx-compliance-disclaimer" style="margin-top: 15px; font-size: 0.85em; border-top: 1px solid #eee; padding-top: 10px;">
        <p><strong>Compliance Note:</strong> Full ingredient lists and product facts are maintained for transparency. Check secondary images for complete profiles.</p>
        <p><em>*These statements have not been evaluated by the Food and Drug Administration. This product is not intended to diagnose, treat, cure, or prevent any disease.</em></p>
      </div>`
    : "";

  return `
    <div class="product-description-output">
      <h3>${title}</h3>
      <p>${title} is engineered to deliver reliable performance and high-conversion visual appeal. This listing is optimized for search visibility and consumer trust.</p>
      
      <h4>Key Specifications & Features</h4>
      <ul>
        ${bulletItems}
        <li>Logistics: Standard shipping weights applied</li>
        <li>Quality Assurance: Certified Professional Grade</li>
      </ul>
      ${regulatoryNotice}
      <h4>Performance Standards</h4>
      <p>This product utilizes the Phoenix Flow technical SEO standard. Description length, tag density, and metadata structure are fully aligned for global marketplace compliance.</p>
      <p style="display: none;">Generated by Phoenix Flow v2.3</p>
    </div>
  `.trim();
}

export default function DescriptionsPage() {
  const { toast } = useToast();
  const [context, setContext] = useState("");
  const [products, setProducts] = useState<ProductSlot[]>(emptySlots);
  const [results, setResults] = useState<GeneratedDescription[]>([]);
  const [loading, setLoading] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const handleUpdate = (index: number, field: keyof Omit<ProductSlot, "id">, value: string) => {
    setProducts((previous) =>
      previous.map((product, productIndex) =>
        productIndex === index ? { ...product, [field]: value } : product,
      ),
    );
  };

  const handleGenerate = () => {
    setLoading(true);
    // Simulate engine logic processing
    window.setTimeout(() => {
      setResults(
        products
          .filter((product) => product.title.trim())
          .map((product) => ({
            title: product.title,
            content: buildDescriptionContent(product, context),
          })),
      );
      setLoading(false);
      toast({ title: "Descriptions Generated", description: "All active slots have been processed." });
    }, 800);
  };

  const copyToClipboard = async (content: string, id: string) => {
    // Strip HTML for clipboard or keep if needed for Shopify
    await navigator.clipboard.writeText(content);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
    toast({ title: "Copied!", description: "HTML content ready for Shopify." });
  };

  const activeCount = products.filter((product) => product.title.trim()).length;

  return (
    <div className="space-y-6">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <FileText className="h-6 w-6 text-primary" /> PHX DESC-GEN v2.0
        </h1>
        <p className="text-muted-foreground mt-1">
          Binary-compliant Shopify descriptions. Enforces 100% SEO alignment and brand identity.
        </p>
      </motion.div>

      <Card className="bg-card/50 border-border/30">
        <CardHeader className="pb-3">
          <CardTitle className="text-lg flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-primary" /> Global Brand Context
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <Textarea
            placeholder="e.g. Focus on durability and outdoor performance, or highlight eco-friendly materials and wellness benefits."
            value={context}
            onChange={(event) => setContext(event.target.value)}
            className="bg-muted/30 border-border/40"
            rows={2}
          />
        </CardContent>
      </Card>

      <Card className="bg-card/50 border-border/30">
        <CardHeader>
          <CardTitle className="flex items-center justify-between text-lg">
            <span>Product Batch Input</span>
            <Badge variant="outline" className="text-primary border-primary/30">
              {activeCount}/5 Slots Active
            </Badge>
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {products.map((product, index) => (
            <div key={product.id} className="grid grid-cols-1 gap-3 md:grid-cols-2 p-3 rounded-lg border border-border/10 bg-muted/10">
              <div className="space-y-1">
                <p className="text-[10px] uppercase font-bold text-muted-foreground ml-1">Title</p>
                <Input
                  placeholder="e.g. Ashwagandha Capsules"
                  value={product.title}
                  onChange={(event) => handleUpdate(index, "title", event.target.value)}
                  className="bg-background/50"
                />
              </div>
              <div className="space-y-1">
                <p className="text-[10px] uppercase font-bold text-muted-foreground ml-1">Features / Materials</p>
                <Input
                  placeholder="60ct, Organic, Made in USA"
                  value={product.features}
                  onChange={(event) => handleUpdate(index, "features", event.target.value)}
                  className="bg-background/50"
                />
              </div>
            </div>
          ))}
          <Button
            onClick={handleGenerate}
            disabled={loading || activeCount === 0}
            className="w-full gradient-phoenix text-primary-foreground font-bold"
          >
            {loading ? (
              <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Process Batch...</>
            ) : (
              <><Sparkles className="mr-2 h-4 w-4" /> Generate {activeCount} Compliant Descriptions</>
            )}
          </Button>
        </CardContent>
      </Card>

      {results.length > 0 && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4">
          <h2 className="text-sm font-bold uppercase tracking-widest text-primary ml-1">Output Preview (Raw HTML)</h2>
          {results.map((result, idx) => (
            <Card key={idx} className="bg-card/30 border-primary/20 overflow-hidden">
              <CardHeader className="flex flex-row items-center justify-between py-3 bg-muted/20">
                <CardTitle className="text-sm font-bold text-primary">{result.title}</CardTitle>
                <Button 
                  variant="ghost" 
                  size="sm" 
                  onClick={() => copyToClipboard(result.content, String(idx))}
                  className="h-8 gap-2"
                >
                  {copiedId === String(idx) ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
                  <span className="text-[10px] uppercase font-bold">Copy HTML</span>
                </Button>
              </CardHeader>
              <CardContent className="pt-4">
                <div className="prose prose-sm prose-invert max-w-none bg-black/20 p-4 rounded-md border border-border/10">
                  <div dangerouslySetInnerHTML={{ __html: result.content }} />
                </div>
              </CardContent>
            </Card>
          ))}
        </motion.div>
      )}
    </div>
  );
}

function Loader2(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 12a9 9 0 1 1-6.219-8.56" />
    </svg>
  );
}