import { Flame, Eye, Pencil, Store, ShoppingBag, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Link } from "react-router-dom";

const permissions = [
  {
    icon: Eye,
    name: "Read your store listings",
    description: "Phoenix Flow reads your active products and listings to generate optimization suggestions.",
  },
  {
    icon: Pencil,
    name: "Update your listings",
    description: "After you review and approve suggestions, Phoenix Flow writes the approved changes back to your store.",
  },
  {
    icon: Store,
    name: "Read your shop info",
    description: "Phoenix Flow reads your shop name and basic details to identify which store the listings belong to.",
  },
  {
    icon: Sparkles,
    name: "AI-powered suggestions",
    description: "Titles, descriptions, tags, and SEO copy are generated by AI and always shown for your approval before anything is applied.",
  },
];

export default function OAuthConsent() {
  return (
    <div className="min-h-screen bg-background flex flex-col items-center justify-center p-6">
      <div className="w-full max-w-lg space-y-8">
        <div className="text-center space-y-3">
          <div className="flex items-center justify-center gap-2">
            <div className="h-10 w-10 rounded-xl gradient-phoenix flex items-center justify-center">
              <Flame className="h-5 w-5 text-primary-foreground" />
            </div>
            <span className="text-2xl font-bold gradient-phoenix-text">Phoenix Flow</span>
          </div>
          <h1 className="text-xl font-semibold">Connect your store to Phoenix Flow</h1>
          <p className="text-sm text-muted-foreground max-w-sm mx-auto">
            Phoenix Flow connects to Shopify and Etsy using official OAuth. We only request the permissions we actually use, and you approve every change before it's applied.
          </p>
        </div>

        <div className="flex justify-center gap-4 text-muted-foreground">
          <div className="flex items-center gap-1.5 text-sm">
            <ShoppingBag className="h-4 w-4" />
            Shopify
          </div>
          <div className="text-border">·</div>
          <div className="flex items-center gap-1.5 text-sm">
            <Store className="h-4 w-4" />
            Etsy
          </div>
        </div>

        <Card className="bg-card/50 border-border/30">
          <CardContent className="p-6 space-y-4">
            <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">What Phoenix Flow can do</p>
            {permissions.map(({ icon: Icon, name, description }) => (
              <div key={name} className="flex gap-3">
                <div className="mt-0.5 h-8 w-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                  <Icon className="h-4 w-4 text-primary" />
                </div>
                <div>
                  <p className="text-sm font-medium">{name}</p>
                  <p className="text-xs text-muted-foreground leading-relaxed">{description}</p>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>

        <div className="space-y-3">
          <Button asChild className="w-full gradient-phoenix text-primary-foreground">
            <Link to="/settings">Get started — connect your store</Link>
          </Button>
          <p className="text-center text-xs text-muted-foreground">
            You will be redirected to Shopify or Etsy to authorize access. Phoenix Flow never stores your store password.
          </p>
        </div>

        <p className="text-center text-xs text-muted-foreground">
          <Link to="/privacy" className="underline hover:text-foreground">Privacy Policy</Link>
          {" · "}
          <Link to="/terms" className="underline hover:text-foreground">Terms of Service</Link>
        </p>
      </div>
    </div>
  );
}
